version: '3.9'

services:
  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/conf/server.crt.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/conf/server.key.pem"
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - '8080:8080'
      - '8443:8443'
  sidecar:
    container_name: sidecar
    build: ./sidecar
    # restart: always
    ports:
      - '7000:7000'
